site_name: crane
docs_dir: doc
theme: readthedocs
theme_center_lead: true
repo_url: https://github.com/ewilde/crane/
pages:
 - ['index.md', 'Home', 'Introduction']
 - ['faq.md', 'Home', 'FAQ']
%crane.commandpages%
 - ['contribution-guidelines.md', 'About', 'Contribution guidelines']
 - ['contributors.md', 'About', 'Contributors']
