site_name: crane
docs_dir: doc
theme: readthedocs
theme_center_lead: true
repo_url: https://github.com/ewilde/crane/
pages:
 - ['index.md', 'Introduction']
%crane.commandpages%
 - ['contributors.md', 'Contributors']
